locale : en
minY: 0
maxY: 255
allowMovementInSafezone: true
allowMovementInWarzone: true
allowPilotInSafezone: true
allowPilotInWarzone: true
allowSinkInSafezone: false
allowSinkInWarzone: true
reduceStrengthOnCraftSink: true
allowFactionSigns: true
craftPermDefaults:
  - LEADER
  - OFFICER
  - MEMBER
  - RECRUIT
  - ALLY