locale : en
allowMovementInSafezone: true
allowMovementInWarzone: true
allowSinkInSafezone: false
allowSinkInWarzone: true
reduceStrengthOnCraftSink: true
allowFactionSigns: true
craftPermDefaults:
  - LEADER
  - OFFICER
  - MEMBER
  - RECRUIT
  - ALLY